# Generated by Django 4.2.1 on 2023-05-25 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_department', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Position_Empl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_position', models.CharField(max_length=250, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='Логин')),
                ('surname', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('secondname', models.CharField(max_length=250, verbose_name='Отчество')),
                ('number_phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('mail', models.CharField(max_length=250, verbose_name='Почта')),
                ('born', models.DateField(verbose_name='Дата рождения')),
                ('date_enter_company', models.DateField(verbose_name='Дата прихода в компанию')),
                ('password', models.CharField(max_length=250, verbose_name='Пароль')),
                ('id_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department')),
                ('id_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.position_empl')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
