# Generated by Django 4.2.1 on 2023-05-25 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_users_is_authorization_users_salary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='users',
            unique_together={('login',)},
        ),
    ]
