# Generated by Django 4.2.1 on 2023-05-26 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_users_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250, verbose_name='Токен')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
            options={
                'verbose_name': 'Токен',
                'verbose_name_plural': 'Токены',
                'unique_together': {('token',)},
            },
        ),
    ]
