# Generated by Django 4.2.1 on 2023-05-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='img',
            field=models.ImageField(default='./static/img/img.png', upload_to=None),
        ),
    ]
