# Generated by Django 4.2.1 on 2023-05-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_users_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='img',
            field=models.ImageField(default='./static/main/img/img.png', upload_to=None),
        ),
    ]
